# Generated by Django 3.1.4 on 2021-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
